#!/usr/bin/env python3
"""Regenerate the repository-owned Noto Sans CJK interface subsets."""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "assets" / "fonts"
CODEPOINTS_FILE = FONT_DIR / "cjk-ui-codepoints.txt"


def interface_codepoints() -> set[int]:
    codepoints = set(range(0x20, 0x7F))
    codepoints.update(range(0xA0, 0x100))
    codepoints.update(range(0x2000, 0x2070))
    codepoints.update(range(0x20A0, 0x20D0))
    codepoints.update(range(0x3000, 0x3040))
    codepoints.add(0xFFFD)

    for source in sorted((ROOT / "lib").rglob("*.dart")):
        for character in source.read_text(encoding="utf-8"):
            value = ord(character)
            if value > 0xFF:
                codepoints.add(value)
    return codepoints


def write_codepoint_manifest(codepoints: set[int]) -> None:
    values = [f"U+{value:04X}" for value in sorted(codepoints)]
    lines = [
        "# Generated by tool/update_cjk_font_subsets.py.",
        "# Regenerate the font assets whenever localized interface text changes.",
    ]
    for start in range(0, len(values), 16):
        lines.append(",".join(values[start : start + 16]))
    CODEPOINTS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def subset(source: Path, target: Path) -> None:
    executable = shutil.which("pyftsubset")
    if executable is None:
        raise SystemExit("pyftsubset is required; install the fonttools package")
    subprocess.run(
        [
            executable,
            str(source),
            f"--output-file={target}",
            f"--unicodes-file={CODEPOINTS_FILE}",
            "--layout-features=*",
            "--glyph-names",
            "--symbol-cmap",
            "--legacy-cmap",
            "--notdef-glyph",
            "--notdef-outline",
            "--recommended-glyphs",
            "--name-IDs=*",
            "--name-languages=*",
            "--no-recalc-timestamp",
        ],
        check=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--simplified-font", required=True, type=Path)
    parser.add_argument("--traditional-font", required=True, type=Path)
    args = parser.parse_args()

    FONT_DIR.mkdir(parents=True, exist_ok=True)
    write_codepoint_manifest(interface_codepoints())
    subset(args.simplified_font, FONT_DIR / "NotoSansSC-UI.ttf")
    subset(args.traditional_font, FONT_DIR / "NotoSansTC-UI.ttf")


if __name__ == "__main__":
    main()
